### ISSUE TITLE
Let's start with basic HTML

### ISSUE THREAD

**Issue by yarkoyarok** [rodarino/tutor#1]
Create file `index.html` and get **exactly** same render at your browser:

<img width="305" alt="image" src="https://user-images.githubusercontent.com/107027368/177013085-4153afaa-efe9-436b-a397-4d89475033dc.png">

**Comment by rodarino** [comment]
```
<!DOCTYPE html>
<html>
<head>
<title>head</title>
</head>

	<body>
	<h2> Hey! Ho! Let's go! </h2>
		<ul>
			<li>Square: <b>29 m<sup>2</sup></b> </li>
			<li>Name: &#8220<i>sandbox</i>&#8221 </li>
			<li>Quote: <i>&laquoLosing all hope is freedom&raquo </i> </li>
		</ul>
	</body>
</html>
```
![а](https://user-images.githubusercontent.com/108618927/177218486-59ce2e24-4d44-463a-bf97-def84f2f88a1.png)
